# File: .github/workflows/workflow.yml

on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/b08dcd28-13fb-473f-96ce-e94a7be07ef3/resourceGroups/contoso-traders-rg1710915               
        scopes-ignore: |
          /subscriptions/b08dcd28-13fb-473f-96ce-e94a7be07ef3/resourceGroups/contoso-traders-rg1710915/providers/microsoft.authorization
     
